%% Build 12 GHz transmitter RF budget
% One representative transmit path:
% 4 GHz IF filter -> LNA -> 8 GHz-LO upconverter -> Wilkinson splitter
% -> PA -> 12 GHz dipole antenna.
%
% The physical transmitter replicates the PA/antenna path for each array
% element. This rfbudget object models one splitter output path.

scriptDir = fileparts(mfilename("fullpath"));
helpersDir = fullfile(scriptDir, "helpers");

%% Required operating point
fIF = 4e9;             % Hz
fLO = 8e9;             % Hz
fRF = fIF + fLO;       % Hz: 12 GHz
BW = 100e6;            % Hz
Pin = -20;             % dBm available input power

assert(fRF == 12e9, "The IF and LO must produce 12 GHz RF.");

lnaFile = fullfile(helpersDir, "CMD240withNF.s2p");
splitterFile = fullfile(helpersDir, "WilkinsonSplitterData.mat");
assert(isfile(lnaFile), "LNA S-parameter file not found: %s", lnaFile);
assert(isfile(splitterFile), ...
    "Wilkinson splitter data file not found: %s", splitterFile);

%% IF section and frequency conversion
ifFilter = rffilter( ...
    Name="IFFilter", ...
    FilterType="InverseChebyshev", ...
    ResponseType="Bandpass", ...
    FilterOrder=5, ...
    PassbandFrequency=fIF + [-BW/2 BW/2], ...
    PassbandAttenuation=3);

lna = amplifier( ...
    Name="LNA", ...
    Model="sparam", ...
    FileName=lnaFile, ...
    OIP3=28, ...
    OP1dB=19, ...
    OPsat=22);

upconverter = modulator( ...
    Name="Upconverter", ...
    ConverterType="Up", ...
    LO=fLO, ...
    Gain=6, ...
    NF=3, ...
    OIP3=32);

%% RF distribution, power amplification, and antenna
splitterData = load(splitterFile, "splitterSparam");
splitter = nport(splitterData.splitterSparam, "WilkinsonSplitter");
splitter.Input = 1;
splitter.Output = 2;
splitter.Termination = 50;

pa = amplifier( ...
    Name="PA", ...
    Model="poly", ...
    Gain=25, ...
    NF=6, ...
    OIP3=45, ...
    OP1dB=33, ...
    OPsat=37.5);

dipoleElement = design(dipole, fRF);
dipoleS = sparameters(dipoleElement, fRF);
dipoleGain = pattern(dipoleElement, fRF, 0, 0);
txAntenna = rfantenna( ...
    Name="DipoleAntenna", ...
    Type="Transmitter", ...
    Gain=dipoleGain, ...
    Z=s2z(dipoleS.Parameters));

%% Build the linear baseline budget
elements = [ifFilter lna upconverter splitter pa txAntenna];
budget = rfbudget( ...
    Elements=elements, ...
    InputFrequency=fIF, ...
    AvailableInputPower=Pin, ...
    SignalBandwidth=BW, ...
    Solver="Friis");

%% Report cumulative results at each stage
stageName = [ ...
    "IF filter"
    "LNA"
    "8 GHz-LO upconverter"
    "Wilkinson splitter (one output)"
    "Power amplifier"
    "12 GHz dipole antenna"];

stageBudget = table( ...
    stageName, ...
    budget.OutputFrequency(:)/1e9, ...
    budget.TransducerGain(:), ...
    budget.NF(:), ...
    budget.OIP3(:), ...
    budget.OutputPower(:), ...
    VariableNames=[ ...
        "Stage"
        "OutputFrequency_GHz"
        "CumulativeGain_dB"
        "CumulativeNF_dB"
        "CumulativeOIP3_dBm"
        "OutputPower_dBm"]);

fprintf("12 GHz transmitter budget: %.1f GHz IF + %.1f GHz LO\n", ...
    fIF/1e9, fLO/1e9);
fprintf("RF = %.1f GHz, BW = %.0f MHz, Pin = %.1f dBm\n\n", ...
    fRF/1e9, BW/1e6, Pin);
disp(stageBudget);
fprintf("Per-path EIRP: %.2f dBm\n", budget.OutputPower(end));
