%% Build Reference RF Budget Analyzer Chain
% Reference chain from "Agentic AI Antenna-to-bits Reference Chain.docx".

clear; clc;

projectRoot = fileparts(mfilename("fullpath"));
helpersDir = fullfile(projectRoot, "helpers");
addpath(helpersDir);

%% Global parameters
fIF = 4e9;
fLO = 8e9;
fRF = 12e9;
BW = 100e6;
Pin = -20;       % dBm
N = 4;           % baseline dipole array

%% Stage 1 - IF filter, BFIC #1
ifFilter = rffilter( ...
    "Name", "IFfilter", ...
    "FilterType", "InverseChebyshev", ...
    "ResponseType", "Bandpass", ...
    "FilterOrder", 5, ...
    "PassbandFrequency", fIF + [-BW/2 BW/2], ...
    "PassbandAttenuation", 3);

%% Stage 2 - Driver amplifier, BFIC #2
driverAmp = amplifier( ...
    "Name", "DriverAmp", ...
    "Model", "sparam", ...
    "FileName", fullfile(helpersDir, "CMD240withNF.s2p"), ...
    "OIP3", 28, ...
    "OP1dB", 19, ...
    "OPsat", 22);

%% Stage 3 - RF tuner / upconverter, BFIC #3
rfTuner = modulator( ...
    "Name", "RFtuner", ...
    "Model", "mod", ...
    "LO", fLO, ...
    "ConverterType", "Up", ...
    "Gain", 6, ...
    "NF", 3, ...
    "OIP3", 32);

%% Stage 4 - Wilkinson corporate splitter, BFIC #4
splitterData = load(fullfile(helpersDir, "WilkinsonSplitterData.mat"), "splitterSparam");
splitter = nport(sparameters(splitterData.splitterSparam), "WilkinsonSplitter");
splitter.Input = 1;
splitter.Output = 2;
splitter.Termination = 50;

%% Stage 5 - Power amplifier
pa = amplifier( ...
    "Name", "PA", ...
    "Model", "poly", ...
    "Gain", 25, ...
    "NF", 6, ...
    "OIP3", 45, ...
    "OP1dB", 33, ...
    "OPsat", 37.5);

%% Stage 6 - Baseline antenna element
rfAntenna = design(dipole, fRF);
antS = sparameters(rfAntenna, fRF);
antennaGain = pattern(rfAntenna, fRF, 0, 0);
budgetAntenna = rfantenna( ...
    "Name", "DipoleAnt", ...
    "Type", "Transmitter", ...
    "Gain", antennaGain, ...
    "Z", s2z(antS.Parameters));

%% RF Budget and analyzer
elements = [ifFilter driverAmp rfTuner splitter pa budgetAntenna];
budget = rfbudget( ...
    "Elements", elements, ...
    "InputFrequency", fIF, ...
    "AvailableInputPower", Pin, ...
    "SignalBandwidth", BW);

rfBudgetAnalyzer(budget);

%% Compact baseline roll-up for the 4-element array
paStage = 5;
paOutputPower = budget.OutputPower(paStage);

antennaArray = design(linearArray("Element", rfAntenna), fRF, rfAntenna);
antennaArray.NumElements = N;
arrayDirectivity = peakRadiation(antennaArray, fRF);
estimatedEIRP = paOutputPower + arrayDirectivity + 10*log10(N);

fprintf("Reference RF budget chain built and loaded in rfBudgetAnalyzer.\n");
fprintf("IF/RF: %.1f GHz -> %.1f GHz, BW %.0f MHz, Pin %.1f dBm\n", ...
    fIF/1e9, fRF/1e9, BW/1e6, Pin);
fprintf("PA output per path: %.2f dBm\n", paOutputPower);
fprintf("4-dipole array directivity: %.2f dBi\n", arrayDirectivity);
fprintf("Estimated array EIRP: %.2f dBm\n", estimatedEIRP);

