%% Build a 12 GHz transmitter RF budget at 20 dBm input power
% This budget represents one output path of the four-way transmitter:
% 4 GHz IF filter -> driver -> 8 GHz-LO upconverter -> Wilkinson output
% -> PA -> 12 GHz dipole. The splitter distributes the signal to four
% equivalent PA/antenna paths; only one path belongs in an rfbudget cascade.

scriptDir = fileparts(mfilename("fullpath"));
helpersDir = fullfile(scriptDir, "helpers");

%% Operating point
fIF = 4e9;
fLO = 8e9;
fRF = fIF + fLO;
BW = 100e6;
Pin = 20; % dBm, available input power at the 4 GHz IF filter

driverFile = fullfile(helpersDir, "CMD240withNF.s2p");
splitterFile = fullfile(helpersDir, "WilkinsonSplitterData.mat");
assert(isfile(driverFile), "Driver S-parameter file not found: %s", driverFile);
assert(isfile(splitterFile), "Splitter S-parameter file not found: %s", splitterFile);

%% BFIC #1: 4 GHz IF filter
ifFilter = rffilter( ...
    Name="IFfilter", ...
    FilterType="InverseChebyshev", ...
    ResponseType="Bandpass", ...
    FilterOrder=5, ...
    PassbandFrequency=fIF + [-BW/2 BW/2], ...
    PassbandAttenuation=3);

%% BFIC #2: measured driver amplifier
driver = amplifier( ...
    Name="DriverAmp", ...
    Model="sparam", ...
    FileName=driverFile, ...
    OIP3=28, ...
    OP1dB=19, ...
    OPsat=22);

%% BFIC #3: 4 GHz IF to 12 GHz RF upconverter
upconverter = modulator( ...
    Name="Upconverter", ...
    LO=fLO, ...
    ConverterType="Up", ...
    Gain=6, ...
    NF=3, ...
    OIP3=32);

%% BFIC #4: one output of the four-way Wilkinson splitter
splitterData = load(splitterFile, "splitterSparam");
splitter = nport(splitterData.splitterSparam, "WilkinsonSplitter");
splitter.Input = 1;
splitter.Output = 2;
splitter.Termination = 50;

%% Final PA and representative 12 GHz dipole
pa = amplifier( ...
    Name="PowerAmp", ...
    Model="poly", ...
    Gain=25, ...
    NF=6, ...
    OIP3=45, ...
    OP1dB=33, ...
    OPsat=37.5);

dipoleElement = design(dipole, fRF);
dipoleSParameters = sparameters(dipoleElement, fRF);
dipoleGain = pattern(dipoleElement, fRF, 0, 0);
txAntenna = rfantenna( ...
    Name="DipoleAntenna", ...
    Type="Transmitter", ...
    Gain=dipoleGain, ...
    Z=s2z(dipoleSParameters.Parameters));

%% Build and report the nonlinear RF budget
% At Pin = 20 dBm, the driver and PA are well above their linear regions.
% HarmonicBalance therefore models their compression rather than merely
% extrapolating the small-signal gains.
elements = [ifFilter driver upconverter splitter pa txAntenna];
budget = rfbudget( ...
    Elements=elements, ...
    InputFrequency=fIF, ...
    AvailableInputPower=Pin, ...
    SignalBandwidth=BW, ...
    Solver="HarmonicBalance", ...
    HarmonicOrder=3);

stage = [ ...
    "IF filter"
    "Driver amplifier"
    "Upconverter"
    "Wilkinson splitter (one output)"
    "Power amplifier"
    "Dipole antenna"];

stageBudget = table( ...
    stage, ...
    budget.OutputFrequency(:)/1e9, ...
    budget.TransducerGain(:), ...
    budget.NF(:), ...
    budget.OIP3(:), ...
    budget.OutputPower(:), ...
    VariableNames=[ ...
        "Stage"
        "OutputFrequency_GHz"
        "CumulativeGain_dB"
        "CumulativeNF_dB"
        "CumulativeOIP3_dBm"
        "OutputPower_dBm"]);

fprintf("12 GHz transmitter RF budget (one splitter output path)\n");
fprintf("IF + LO = RF: %.1f + %.1f = %.1f GHz\n", ...
    fIF/1e9, fLO/1e9, fRF/1e9);
fprintf("Bandwidth: %.0f MHz; Pin: %.1f dBm\n\n", BW/1e6, Pin);
disp(stageBudget);

driverHeadroom = driver.OP1dB - budget.OutputPower(2);
paHeadroom = pa.OP1dB - budget.OutputPower(5);
fprintf("Driver OP1dB headroom: %.2f dB\n", driverHeadroom);
fprintf("PA OP1dB headroom: %.2f dB\n", paHeadroom);
fprintf("Per-path EIRP: %.2f dBm\n", budget.OutputPower(end));
